blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://mellow-artificial-intelligence.github.io/open-xtract/
    about: Check the documentation for usage guides and examples
